import React from "react";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import axios from "axios";
import { IParams, IProduct } from "../../components/Types";
import SingleProduct from "../../components/SingleProduct";
import Advert from "../../components/Advert";
import InterestedProducts from "../../components/InterestedProducts";

const Product: NextPage<{ product: IProduct }> = ({ product }) => {
  console.log(product);
  return (
    <div>
      <Head>
        <title>Products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SingleProduct product={product} />
      <Advert/>
      <InterestedProducts/>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { id } = context.params as IParams;
  console.log(id);
  const res = await axios.get<IProduct>(
    `http://localhost:3000/api/products/${id}`
  );
  const product = res.data;

  return {
    props: {
      product,
    },
  };
};

export default Product;
