import React, { useContext } from "react";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { IParams, IProduct } from "../../components/Types";
import SingleProduct from "../../components/SingleProduct";
import Advert from "../../components/Advert";
import InterestedProducts from "../../components/InterestedProducts";
import Menu from "../../components/Menu";
import { MenuContext } from "../../context/MenuContext";
import axios from "axios";
import { BASE_URL } from "../../util/url";

const Product: NextPage<{ product: IProduct }> = ({ product }) => {
  const { state } = useContext(MenuContext);

  return (
    <div>
      <Head>
        <title>Products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {state.menu && <Menu />}
      <SingleProduct product={product} />
      <Advert/>
      <InterestedProducts/>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
 
  const { id } = context.params as IParams;
  const res = await axios.get<IProduct>(
    `${BASE_URL}products/${id}`
  );
  const product = res.data;

  return {
    props: {
      product,
    },
  };
};

export default Product;
