import React, { useContext } from "react";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";

import { BASE_URL } from "../../util/url";
import FilterProducts from "../../components/FilterProducts";
import { IProduct } from "../../components/Types";
import Menu from "../../components/Menu";
import { MenuContext } from "../../context/MenuContext";
// import { dbConnect } from "../../util/mongo";

const Products: NextPage<{ products: IProduct[] }> = ({ products }) => {
  const { state } = useContext(MenuContext);

  return (
    <div style={{ position: "relative" }}>
      <Head>
        <title>Products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {state.menu && <Menu />}
      <FilterProducts products={products} />
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  // await dbConnect();
  let products;
  if (query.category || query.category !== "Tüm Ürünler") {
    // console.log("QUERY",query);
    const res = await fetch(
      `${BASE_URL}products?cat=${decodeURIComponent(query.category as string)}`
    );
    products = (await res.json()) as IProduct[];
  } else {
    console.log(query);
    // res = await axios.get<IProduct[]>(`${BASE_URL}products`);
    const res = await fetch(`${BASE_URL}products`);
    products = (await res.json()) as IProduct[];
  }

  return {
    props: {
      products,
    },
  };
};

export default Products;
