import React from "react";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";

import { BASE_URL } from "../../util/url";
import FilterProducts from "../../components/FilterProducts";
import { IProduct } from "../../components/Types";

const Products: NextPage<{ products: IProduct[] }> = ({ products }) => {

  return (
    <div style={{ position: "relative" }}>
      <Head>
        <title>Products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FilterProducts products={products} />
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async ({
  query: { category },
}) => {
  let products;

  if (category || category !== "Tüm Ürünler") {
    const res = await fetch(
      `${BASE_URL}products?cat=${decodeURIComponent(category as string)}`
    );
      
    products = (await res.json()) as IProduct[];

  } else {
    const res = await fetch(`${BASE_URL}products`);
    products = (await res.json()) as IProduct[];
  }
  return {
    props: {
      products,
    },
  };
};

export default Products;
