import React, { useContext } from "react";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import FilterProducts from "../../components/FilterProducts";
import axios from "axios";
import { IProduct } from "../../components/Types";
import { MenuContext } from "../../context/MenuContext";
import Menu from "../../components/Menu";
import { publicRequest } from "../../requestMethod";

const Products: NextPage<{ products: IProduct[] }> = ({ products }) => {
  const { state } = useContext(MenuContext);

  return (
    <div style={{ position: "relative"}}>
      <Head>
        <title>Products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {state.menu && <Menu />}
      <FilterProducts products={products} />
    </div>
  );
};
export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  let res;
  if (query.category) {
    
    res = await publicRequest.get<IProduct>(
      `/products?cat=${decodeURIComponent(query.category as string)}`
    );
    
  } else {
    console.log("aaa")
    res = await publicRequest.get<IProduct>("/products");
    console.log("bbb")
  }

  return {
    props: {
      products: res.data,
    },
  };
};
export default Products;
