import type { NextPage } from "next";
import Head from "next/head";
import Categories from "../components/Categories";
import Products from "../components/Products";
import Slider from "../components/Slider";
import Video from "../components/Video";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500;600;700;800&display=swap" rel="stylesheet"
        />
      </Head>
      <Slider/>
      <Products/>
      <Categories/>
      <Video/>
    </div>
  );
};

export default Home;
